import React, { Suspense, lazy } from 'react';
import { SiteProvider, useSite } from './context/SiteContext';
import { Header } from './components/Header';
import { Hero } from './components/Hero';
import { BookingModal } from './components/BookingModal';
import { StickyCTA } from './components/StickyCTA';
import { MouseParticles } from './components/MouseParticles';
import { motion, useScroll, useSpring } from 'motion/react';
import { ContentProvider, useContent } from './context/ContentContext';

const AdminDashboard = lazy(() => import('./components/AdminDashboard').then(module => ({ default: module.AdminDashboard })));

const Services = lazy(() => import('./components/Services').then(module => ({ default: module.Services })));
const WhyChooseUs = lazy(() => import('./components/WhyChooseUs').then(module => ({ default: module.WhyChooseUs })));
const Solutions = lazy(() => import('./components/Solutions').then(module => ({ default: module.Solutions })));
const EcommerceSaas = lazy(() => import('./components/EcommerceSaas').then(module => ({ default: module.EcommerceSaas })));
const ToolsGrid = lazy(() => import('./components/ToolsGrid').then(module => ({ default: module.ToolsGrid })));
const Workflow = lazy(() => import('./components/Workflow').then(module => ({ default: module.Workflow })));
const Testimonials = lazy(() => import('./components/Testimonials').then(module => ({ default: module.Testimonials })));
const FAQ = lazy(() => import('./components/FAQ').then(module => ({ default: module.FAQ })));
const Blog = lazy(() => import('./components/Blog').then(module => ({ default: module.Blog })));
const HiddenTrigger = lazy(() => import('./components/HiddenTrigger').then(module => ({ default: module.HiddenTrigger })));
const AdminPanel = lazy(() => import('./components/AdminPanel').then(module => ({ default: module.AdminPanel })));
const Footer = lazy(() => import('./components/Footer').then(module => ({ default: module.Footer })));

const PrivacyPolicy = lazy(() => import('./components/Policies').then(module => ({ default: module.PrivacyPolicy })));
const TermsOfService = lazy(() => import('./components/Policies').then(module => ({ default: module.TermsOfService })));
const CookiePolicy = lazy(() => import('./components/Policies').then(module => ({ default: module.CookiePolicy })));
const Disclaimer = lazy(() => import('./components/Policies').then(module => ({ default: module.Disclaimer })));

const ScrollProgress = () => {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });
  
  return (
    <motion.div
      className="fixed top-0 left-0 right-0 h-[3px] z-[99999] origin-left pointer-events-none"
      style={{ 
        scaleX, 
        backgroundColor: 'var(--color-brand-blue-val, #4F8EF7)',
        boxShadow: '0 0 10px var(--color-brand-blue-val, #4F8EF7), 0 0 5px var(--color-brand-blue-val, #4F8EF7)'
      }}
    />
  );
};

const CustomSection: React.FC<{ id: string, title: string, content: string }> = ({ id, title, content }) => {
  return (
    <section className="py-24 relative overflow-hidden" id={id}>
      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <motion.div
           initial={{ opacity: 0, y: 20 }}
           whileInView={{ opacity: 1, y: 0 }}
           viewport={{ once: true }}
           className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-5xl font-bold mb-6 text-white">{title}</h2>
          <div className="w-24 h-1 bg-brand-blue mx-auto rounded-full mb-8"></div>
        </motion.div>
        
        <div className="bg-black/40 shadow-[inset_0_4px_12px_rgba(0,0,0,0.8),0_1px_1px_rgba(255,255,255,0.05)] border border-black/80 p-8 md:p-12 rounded-3xl text-center text-gray-300 leading-relaxed text-lg max-w-4xl mx-auto">
          {content}
          
          <div className="mt-8 flex justify-center">
            <div className="text-xs bg-brand-blue/10 text-brand-blue px-3 py-1 rounded-full border border-brand-blue/20">
              Generated by AI Tools
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

const MainContent = () => {
  const { config } = useSite();

  const renderSection = (id: string) => {
    if (config.sections[id] === false) return null;

    switch (id) {
      case 'hero': return <Hero key={id} />;
      case 'services': return <Suspense key={id} fallback={<div className="h-96" />}><Services /></Suspense>;
      case 'whyUs': return <Suspense key={id} fallback={<div className="h-96" />}><WhyChooseUs /></Suspense>;
      case 'solutions': return <Suspense key={id} fallback={<div className="h-96" />}><Solutions /></Suspense>;
      case 'ecommerce': return <Suspense key={id} fallback={<div className="h-96" />}><EcommerceSaas /></Suspense>;
      case 'tools': return <Suspense key={id} fallback={<div className="h-96" />}><ToolsGrid /></Suspense>;
      case 'workflow': return <Suspense key={id} fallback={<div className="h-96" />}><Workflow /></Suspense>;
      case 'testimonials': return <Suspense key={id} fallback={<div className="h-96" />}><Testimonials /></Suspense>;
      case 'faq': return <Suspense key={id} fallback={<div className="h-96" />}><FAQ /></Suspense>;
      case 'blog': return <Suspense key={id} fallback={<div className="h-96" />}><Blog /></Suspense>;
      default:
        const customSec = config.customSections?.find(s => s.id === id);
        if (customSec) {
          return <CustomSection key={id} id={customSec.id} title={customSec.title} content={customSec.content} />;
        }
        return null;
    }
  };

  return (
    <main>
      {config.sectionOrder.map((id, index) => (
        <React.Fragment key={id}>
          {renderSection(id)}
          {index < config.sectionOrder.length - 1 && <div className="glow-divider" />}
        </React.Fragment>
      ))}
    </main>
  );
};

export default function App() {
  return (
    <ContentProvider>
      <SiteProvider>
        <AppContent />
      </SiteProvider>
    </ContentProvider>
  );
}

function AppContent() {
  const { config } = useSite();
  const { content } = useContent();
  const isHome = config.currentRoute === 'home' || !config.currentRoute;

  const isAdminPath = window.location.pathname.replace(/\/$/, '') === '/admin';

  if (isAdminPath) {
    return (
      <Suspense fallback={
        <div className="min-h-screen flex items-center justify-center bg-[#07070F] text-white">
          <div className="w-12 h-12 border-4 border-brand-blue border-t-transparent rounded-full animate-spin"></div>
        </div>
      }>
        <AdminDashboard />
      </Suspense>
    );
  }

  return (
    <div 
      className="relative min-h-screen selection:bg-[color:var(--color-brand-purple-val)] selection:text-white pb-20 bg-cover bg-center bg-fixed transition-colors duration-300"
      style={{
        backgroundImage: config.backgroundImage ? `url(${config.backgroundImage})` : 'none',
        backgroundColor: config.backgroundColor,
        ['--color-brand-blue-val' as any]: content.identity.primaryColor,
        ['--color-brand-purple-val' as any]: content.identity.secondaryColor,
        ['--color-brand-green-val' as any]: content.identity.accentColor,
      }}
    >
      <ScrollProgress />
      <Header />
      
      {isHome ? (
        <MainContent />
      ) : (
        <Suspense fallback={<div className="min-h-screen flex items-center justify-center pt-24"><div className="w-10 h-10 border-4 border-brand-blue border-t-transparent rounded-full animate-spin"></div></div>}>
          <div className="pt-32 pb-24 px-6 max-w-4xl mx-auto min-h-screen">
            {config.currentRoute === 'privacy' && <PrivacyPolicy />}
            {config.currentRoute === 'terms' && <TermsOfService />}
            {config.currentRoute === 'cookies' && <CookiePolicy />}
            {config.currentRoute === 'disclaimer' && <Disclaimer />}
          </div>
        </Suspense>
      )}
      
      <Suspense fallback={null}>
        <Footer />
      </Suspense>

      {/* Hidden Admin Features */}
      <Suspense fallback={null}>
        <HiddenTrigger />
        <AdminPanel />
      </Suspense>

      {/* Global Consult Booking Dialog */}
      <BookingModal />
      <StickyCTA />
      
      {/* Visual Effects */}
      <MouseParticles />
    </div>
  );
}
